#!/usr/bin/env zsh

(( $+commands[rustup] )) || {
  unset '_comps[rustup]'
  _default "$@"
  return
}

{
  builtin source <(rustup completions zsh rustup)
} always {
  (( $+functions[_rustup] )) && _comps[rustup]=_rustup || unset '_comps[rustup]'
}
