#!/usr/bin/env zsh

if [[ -v functions[-z4h-test-func] ]]; then
  builtin unfunction -- -z4h-test-func
fi
functions[-z4h-test-func]="$1" 2>/dev/null              || builtin return 1
[[ -v functions[-z4h-test-func] ]]                      || builtin return 1
builtin unfunction -- -z4h-test-func
functions[-z4h-test-func]="$1"$'\ndo\ndone' 2>/dev/null || builtin return 0
[[ -v functions[-z4h-test-func] ]]                      || builtin return 0
builtin unfunction -- -z4h-test-func
return 1
