#!/usr/bin/env zsh

eval "$_z4h_opt"

[[ -w $TTY ]] || return

if [[ -n $_Z4H_TMUX ]]; then
  (( ${+_z4h_saved_screen} )) || return
  print -rn -- "$_z4h_saved_screen" >"$TTY"
elif [[ -n $Z4H_SSH && -n $_Z4H_SSH_MARKER ]]; then
  printf '\001z4h.%s%s' "$_Z4H_SSH_MARKER" 'restore-screen  ' >"$TTY"
else
  return 1
fi
