#!/usr/bin/env zsh

eval "$_z4h_opt"

local file=$Z4H_PACKAGE_DIR/zsh-syntax-highlighting.zsh
[[ -e $file ]] || return 0

local code
code=$(<$file) || return

local orig='

'
local sub='

[[ -n ${ZSH_SCRIPT+X}${ZSH_EXECUTION_STRING+X} ]] && return

'
print -r -- ${code/$orig/$sub} >$file
