#!/usr/bin/env zsh

local home=~
local zdotdir=${${${(q)ZDOTDIR}/#${(q)home}/'~'}//\%/%%}
local z4h=${${${(q)Z4H}/#${(q)home}/'~'}//\%/%%}
print -Pru2 -- ''
print -Pru2 -- '%F{3}z4h%f: %B'${1//\%/%%}'%b %F{1}failed%f'
print -Pru2 -- ''
print -Pru2 -- 'See error messages above to identify the culprit.'
print -Pru2 -- ''
print -Pru2 -- 'Edit Zsh configuration:'
print -Pru2 -- ''
print -Pru2 -- '  %F{2}'${(q)${VISUAL:-${EDITOR:-vi}}}'%f %U'$zdotdir'/.zshrc%u'
if [[ $1 != update ]]; then
  print -Pru2 -- ''
  print -Pru2 -- 'Retry Zsh initialization:'
  print -Pru2 -- ''
  print -Pru2 -- '  %U%F{2}exec%u zsh%f'
fi
print -Pru2 -- ''
print -Pru2 -- 'If nothing helps and you are about to give up:'
print -Pru2 -- ''
print -Pru2 -- '  %F{5}# nuke the entire site from orbit'
print -Pru2 -- '  %F{2}%Usudo%u rm%f -rf -- %U'$z4h'%u'
if (( $+commands[curl] )); then
  print -Pru2 -- ''
  print -Pru2 -- 'Give up and start over:'
  print -Pru2 -- ''
  print -Pru2 -- '  %F{2}sh%f -c %F{3}"%f$(%F{2}curl%f -fsSL %Uhttps://raw.githubusercontent.com/romkatv/zsh4humans/v5/install%u)%F{3}"%f'
  print -Pru2 -- ''
elif (( $+commands[wget] )); then
  print -Pru2 -- ''
  print -Pru2 -- 'Give up and start over:'
  print -Pru2 -- ''
  print -Pru2 -- '  %F{2}sh%f -c %F{3}"%f$(%F{2}wget%f -O- %Uhttps://raw.githubusercontent.com/romkatv/zsh4humans/v5/install%u)%F{3}"%f'
  print -Pru2 -- ''
fi
