#!/usr/bin/env zsh

if (( ${+_z4h_redraw_fd} )); then
  zle -F "$_z4h_redraw_fd"
  exec {_z4h_redraw_fd}>&-
  unset _z4h_redraw_fd
fi

if [[ -v region_highlight &&
      ( ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ) ]]; then
  _zsh_highlight
  -z4h-autosuggest-fetch
fi
