#!/usr/bin/env zsh

[[ -v _z4h_tty_fd ]] || return

builtin echoti civis >&$_z4h_tty_fd
builtin print -rn -- $'\e[H\e[2J' >&$_z4h_tty_fd
builtin zle .reset-prompt
builtin zle -R
builtin print -rn -- $'\e[3J' >&$_z4h_tty_fd
builtin echoti cnorm >&$_z4h_tty_fd
