#!/usr/bin/env zsh

[[ -v _z4h_tty_fd ]] || return

builtin echoti civis >&$_z4h_tty_fd
local -i cursor_x cursor_y
-z4h-get-cursor-pos || cursor_y=0
builtin print -rnu $_z4h_tty_fd -- "${(pl:$((2 * LINES - cursor_y))::\n:)}"$'\e[H\e[2J'
builtin zle .reset-prompt
builtin zle -R
-z4h-cursor-show
