#!/usr/bin/env zsh

local -i cursor=CURSOR
{
  if [[ $KEYMAP == vicmd && -n $BUFFER ]]; then
    CURSOR=$((${#BUFFER} - 1))
  else
    CURSOR=${#BUFFER}
  fi
  zle autosuggest-accept
} always {
  CURSOR=cursor
}
