#!/usr/bin/env zsh

[[ -v _z4h_tty_fd ]] || return

builtin echoti civis >&$_z4h_tty_fd
local -i cursor_x cursor_y
-z4h-get-cursor-pos
builtin print -rn -- "${(pl:$((2 * LINES - cursor_y))::\n:)}"$'\e[H\e[2J' >&$_z4h_tty_fd
builtin zle .reset-prompt
builtin zle -R
builtin echoti cnorm >&$_z4h_tty_fd
