#!/usr/bin/env zsh

builtin zle || builtin exit 0
if [[ "$CONTEXT" == start && -z "${BUFFER// /}" ]]; then
  typeset -g precmd_functions=(z4h-eof)
  builtin zle -w accept-line
else
  zle -w delete-char-or-list
fi
