#!/usr/bin/env zsh

emulate -L zsh -o extended_glob

local last=-1
local out=-1
local content=

function maybe-flush() {
  if (( last >= 0 )); then
    printf '[%s, "o", "%s"]\n' "$out" "$content"
  fi
}

while read -r line; do
  if [[ $line != (#b)'['([0-9.]#)', "o", "'(*)'"]' ]]; then
    print -r -- $line
    continue
  fi
  local t=$match[1]
  local data=$match[2]
  if (( t - last < 0.1 )); then
    content+=$data
  else
    maybe-flush
    out=$t
    content=$data
  fi
  last=$t
done

maybe-flush
